spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      auto-index-creation: true
      database: "bank"
      uri: "mongodb://localhost:27017/bank"
springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    disable-swagger-default-url: true
    path: /


